BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: user_distance_input
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'Convert m to km'
        Label:
            text: 'am Label'